### ISSUE TITLE
Can we test Quickstart Guide with minikube?

### ISSUE THREAD

**Issue by gxcuit** [confidential-containers/documentation#67]
Hi 
Recently I follow the [Quickstart Guide](https://github.com/confidential-containers/documentation/blob/main/quickstart.md) with minikube.

I have finished [Deploy the the operator](https://github.com/confidential-containers/documentation/blob/main/quickstart.md#deploy-the-the-operator). Everything looks fine. 

```
NAMESPACE                        NAME                                              READY   STATUS    RESTARTS   AGE
confidential-containers-system   cc-operator-controller-manager-5df7584679-c5ttt   2/2     Running   0          79s

```

Then I try to [Create the custom resource](https://github.com/confidential-containers/documentation/blob/main/quickstart.md#create-the-custom-resource). I changed the ccruntime.yaml with the following:

```
ccNodeSelector:
    matchLabels:
             node-role.kubernetes.io/control-plane: ""
            # node-role.kubernetes.io/worker: ""
```

I did not get the corresponding pods running. Is there anything wrong?
```
NAMESPACE                        NAME                                              READY   STATUS    RESTARTS   AGE
confidential-containers-system   cc-operator-controller-manager-5df7584679-c5ttt   2/2     Running   0          79s

```
